export const Styles = {
  container: {
    backgroundColor: "#0f0f0f",
    color: "##a1a1aa",
    mt: 10,
  },
  title: {
    fontWeight: "bold",
    maxWidth: "max-content",
    background: "-webkit-linear-gradient(0deg, #fafafa, #a1a1aa)",
    WebkitBackgroundClip: "text",
    WebkitTextFillColor: "transparent",
    marginBottom: "2rem",
  },
  card: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: "transparent",
    border: "3px solid ##a1a1aa",
    borderRadius: "16px",
    textAlign: "center",
    padding: ".75rem",
    boxShadow: "0px 4px 10px rgba(0, 0, 0, 0.5)",
    transition: "background 0.3s ease",
    backgroundColor: "#27272a",
  },
  image: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    aspectRatio: "1 / 1",
    borderRadius: "12px",
    marginBottom: "1rem",
  },
  cardContent: {
    padding: "16px 0",
    margin: 0,
    width: "100%",
  },
  cardTitle: {
    fontWeight: "bold",
    marginBottom: "1rem",
    fontSize: "22px",
    color: "#e5e7eb",
    textAlign: "left",
  },
  Visit: {
    display: "flex",
    justifyContent: "space-between ",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "0.5rem",
  },
  techContainer: {
    display: "flex",
    justifyContent: "center",
    flexWrap: "wrap",
    gap: "0.5rem",
  },
  chip: {
    backgroundColor: "#1e1e1e",
    color: "#a1a1aa",
    fontWeight: "bold",
  },
  iconButton: {
    color: "#09090b",
    backgroundColor: "#38bdf8",
    borderRadius: ".5rem",
    width: "2.75rem",
    height: "2.75rem",
  },
};
