const navStyles = {
  root: {
    position: "fixed",
    width: "100%",
    top: 0,
    left: 0,
    zIndex: 1000,
  },
  navbarContainer: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "1rem 2rem",
    backgroundColor: "rgba(24, 24, 27, 0.9)",
    backdropFilter: "blur(10px)",
    borderRadius: "20px",
    margin: "10px",
  },
  logo: {
    width: "50px",
  },
  navWrapper: {
    display: { xs: "none", md: "flex" },
    position: "relative",
    backgroundColor: "#2f2f2f",
    borderRadius: "50px",
    padding: "0.25rem",
    overflow: "hidden",
  },
  slidingBackground: (activeIndex, navLength) => ({
    position: "absolute",
    top: 0,
    left: 0,
    width: `${100 / navLength}%`,
    height: "100%",
    background: "#fafafa",
    borderRadius: "20px",
    transition: "transform 0.3s ease-in-out",
    transform: `translateX(${activeIndex * 100}%)`,
  }),
  navButton: (isActive) => ({
    zIndex: 1,
    flex: 1,
    color: isActive ? "#18181b" : "#bbb",
    fontWeight: "bold",
    textTransform: "none",
    transition: "color 0.3s",
  }),
  contactButton: {
    display: { xs: "none", md: "block" },
    background: "#fafafa",
    color: "#18181b",
    fontWeight: "bold",
    borderRadius: "20px",
    textTransform: "none",
    transition: "all 0.3s",
  },
  menuButton: {
    display: { xs: "block", md: "none" },
  },
  mobileMenu: {
    display: { xs: "flex", md: "none" },
    flexDirection: "column",
    position: "absolute",
    top: "100%",
    left: 0,
    width: "100%",
    backgroundColor: "rgba(24, 24, 27, 0.9)",
    backdropFilter: "blur(10px)",
    borderRadius: "10px",
    padding: "1rem",
  },
  mobileNavButton: (isActive) => ({
    color: isActive ? "#18181b" : "#fff",
    fontWeight: "bold",
    textTransform: "none",
    transition: "color 0.3s",
    "&:hover": {
      color: "#e52e71",
    },
  }),
};

export default navStyles;
